### ISSUE TITLE
Feature request: Event Timetable

### ISSUE THREAD

**Issue by dominik-merdzik** [Paulmski/Discord-Bot#6] opened 2021-12-10 04:54 UTC
We used google spreadsheets throughout semester one to keep track of all of our assignments and tests but making a bot to do it for us is a lot more efficient! Our beginning objective is to make the bot automatically list events that will show what classes we have for the week and what room they are in. This will let students click the event tab and see what time the class is, what room it's in, and a description of what we're going to be learning

**Features** 
 -  Automatically add events (Date, class, room number, description...)
 - Let people interact with the event in case class is postponed or canceled

 Any other ideas feel free to add them below!

**Comment by tuanyvan** [comment] 2021-12-17 19:05
I did some reading on the Discord documentation and [creating Guild Scheduled Events is possible](https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event) through HTTP requests. This isn't done by `discord.py` itself, so we need to make use of its `http.py` request function and classes to do this.

For `discord.py`, there is limited documentation, so I will detail what we would need to do for this feature:

1. Create a JSON payload to send out with the HTTP request. The required parameters to [create an event are in the documentation here](https://discord.com/developers/docs/resources/guild-scheduled-event#create-guild-scheduled-event). We can do this with a Python dictionary and we would have to assign the values for each class & start/end time in `ISO8601` format from somewhere.

2. From the `discord.http` subpackage, we need to import `Route`; `from discord.http import Route`. The Route object takes the following arguments in the `__init__` function parameters
```python
class Route:
    BASE = 'https://discord.com/api/v7'

    def __init__(self, method, path, **parameters)
```
where `method` is a verb like "GET", "POST", "PATCH", `path` is the part of the URL we append to `BASE = 'https://discord.com/api/v7'`. 

The `Route` object has the properties `url`, `method`, and `bucket` which "is just method + path w/ major parameters [channel_id and guild_id]" according to the code comment. The `bucket` needs a `guild_id`, so we can pass it as keyword argument, meaning we call the Route object as such to create a new Scheduled Event...
```python
route_object = Route("POST", "/guilds/{guild.id}/scheduled-events", guild_id=OUR_GUILD_ID)
```

3. Take advantage of the fact the `Bot` object imports the entire `discord` package, make use of the `http.py` subpackage. From here, we can use the `http.py`'s `HTTPClient` class to call `request`, which takes the properties of a Route object (`bucket`, `method`, `url`) and the payload we made in Step 1 as a keyword argument `json`.

Thus, to make the HTTP request to Discord to make a scheduled event, we need something like the following:
```python
def make_scheduled_event(guild_id):
    payload = {
        # Insert values for each JSON property here...
    }

    route_object = Route(
        'POST',
        '/guilds/{guild_id}/scheduled-events',
        guild_id=guild_id
    )

    return bot.http.request(r, json=payload)
```

Obviously it isn't as "easy as 123", but the lack of documentation for this feature means we need to use whatever we can get from the `discord.py` package.

**Comment by Paulmski** [comment] 2021-12-17 19:18
Too bad we need to manually interact with the api via https.

We would have to implement some way for people to interact with the event with commands. Perhaps using a command like `!event [subcommands] {args}` this is where implementation is really important because it'll get messy quick otherwise.

**Comment by Paulmski** [comment] 2021-12-31 04:38
Duplicate of #38

**Closed by Paulmski** 2021-12-31 04:38 UTC
Labels: enhancement
